config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/index'
  get 'pages/html'
  get 'pages/css'
  get 'pages/javascript'
  root to: 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
  	resources :postcomments 
  end
  get "postcomments/:postcomment_id/vote", to: "postcomments#vote",as: "vote"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :postcomments
	belongs_to :category
	 
	validates :title, length: { in: 1..30 }
	validates :body, length: { in: 10..5012 }
	validates :title, uniqueness: true
	validates :title, presence: true
	
end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
	belongs_to :user
	belongs_to :post
	has_many :votes


	validates :text, presence: true
	validates :text, length: { in: 4..256 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :posts
         has_many :postcomments
         has_many :votes
                  has_many :post1s
         has_many :postcomments1
                  has_many :vote1s
                  has_many :post2s
         has_many :postcomment2s
                  has_many :vote2s

 validates :nickname, :email, :password_confirmation, :password, presence: true
 validates :nickname, :email, uniqueness: true

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/default.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :user
	belongs_to :postcomment
end

app/controllers/application_controller.rb
 class ApplicationController < ActionController::Base
  before_action :devise_sign_up_params, if: :devise_controller?
  protect_from_forgery with: :exception


  private

  def devise_sign_up_params
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :nickname, :avatar])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end

  def html
  @posts = Post.where(category_id: 1)
  end

  def css
  @posts = Post.where(category_id: 2)
  end

  def javascript
  @posts = Post.where(category_id: 3)
  end
end

app/controllers/postcomments_controller.rb
class PostcommentsController < ApplicationController
	before_action :authenticate_user!

	def create
		params[:postcomment][:post_id] = params[:post_id]
		params[:postcomment][:user_id] = current_user.id
		@comment = Postcomment.create(postcomments_params)
  if @comment.save
    redirect_to post_path(params[:post_id])
  else 
    @comment.errors.full_messages.each do |msg|
     @msg = msg
    end  
    flash[:notice] = "#{@msg}"
    redirect_to post_path(params[:post_id])
  end
end

def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.postcomments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  def vote
    @comment=Postcomment.find(params[:postcomment_id])
    @vote=Vote.where(user_id: current_user.id, postcomment_id: @comment.id).first
    if @vote != nil
      @vote.destroy
    else
      @vote=Vote.create(user_id: current_user.id, postcomment_id: @comment.id)
    end
    redirect_to post_path(@comment.post.id)
  end

private

	def postcomments_params
		params.require(:postcomment).permit(:user_id, :post_id, :text)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show,:edit,:update,:destroy]
  def new
  @post = Post.new
  end 

  def show
    @comments = Postcomment.where(post_id: @post.id)
    @votes={}
    @comments.each do |comment|
      @votes[comment.id]=Vote.where(postcomment_id: comment.id).count
    end
  end

  def create
    pp params[:post][:category_id]=params[:category_id]
    pp params[:post][:user_id]=current_user.id
  	pp @post = Post.create(post_params)
  	if @post.save
  		redirect_to pages_html_path
  	else
  		render 'new'
  	end

  end
  
  def destroy
  	@post.destroy
  	redirect_to root_path
  end

  def edit
  end

  def update
  	@post.update(post_params)
  	redirect_to root_path
  end

  private
  	def post_params
  		params.require(:post).permit(:user_id,:title,:body,:category_id)
	
  	end

  	def set_post
  		@post = Post.find(params[:id])
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/postcomments_helper.rb
module PostcommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
<style>
.container-fluid a{
  text-decoration:none;
  color: grey;
}

nav{
  background-color: #0d0d0d;
}
</style>

<nav>
  <div class="container-fluid">
    <div class="navbar-header">
    <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>
   

    <ul class="nav navbar-nav navbar-right">
    <% if current_user.nil? %>
    <li>
    <%= link_to user_session_path do %>
      <i class="glyphicon glyphicon-user"></i> Login
      <%end%>
      </li>
      <% else %> 
      <li>
      <%= link_to destroy_user_session_path, method: :delete do %>
      <i class="glyphicon glyphicon-log-in"></i> Logout
  <%end%>
      </li>
       <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/_header.html.erb
<style >
  .fade-carousel {
    position: relative;
    height: 100vh;
}
.fade-carousel .carousel-inner .item {
    height: 100vh;
}
.fade-carousel .carousel-indicators > li {
    margin: 0 2px;
    background-color: #f39c12;
    border-color: #f39c12;
    opacity: .7;
}
.fade-carousel .carousel-indicators > li.active {
  width: 10px;
  height: 10px;
  opacity: 1;
}


.hero {
    position: absolute;
    top: 50%;
    left: 50%;
    z-index: 3;
    color: #fff;
    text-align: center;
    text-transform: uppercase;
    text-shadow: 1px 1px 0 rgba(0,0,0,.75);
      -webkit-transform: translate3d(-50%,-50%,0);
         -moz-transform: translate3d(-50%,-50%,0);
          -ms-transform: translate3d(-50%,-50%,0);
           -o-transform: translate3d(-50%,-50%,0);
              transform: translate3d(-50%,-50%,0);
}
.hero h1 {
    font-size: 6em;    
    font-weight: bold;
    margin: 0;
    padding: 0;
}

.fade-carousel .carousel-inner .item .hero {
    opacity: 0;
    -webkit-transition: 2s all ease-in-out .1s;
       -moz-transition: 2s all ease-in-out .1s; 
        -ms-transition: 2s all ease-in-out .1s; 
         -o-transition: 2s all ease-in-out .1s; 
            transition: 2s all ease-in-out .1s; 
}
.fade-carousel .carousel-inner .item.active .hero {
    opacity: 1;
    -webkit-transition: 2s all ease-in-out .1s;
       -moz-transition: 2s all ease-in-out .1s; 
        -ms-transition: 2s all ease-in-out .1s; 
         -o-transition: 2s all ease-in-out .1s; 
            transition: 2s all ease-in-out .1s;    
}


.btn.btn-lg {padding: 10px 40px;}
.btn.btn-hero,
.btn.btn-hero:hover,
.btn.btn-hero:focus {
    color: #f5f5f5;
    background-color: #1abc9c;
    border-color: #1abc9c;
    outline: none;
    margin: 20px auto;
}

.fade-carousel .slides .slide-1, 
.fade-carousel .slides .slide-2,
.fade-carousel .slides .slide-3 {
  height: 100vh;
  background-size: cover;
  background-position: center center;
  background-repeat: no-repeat;
}
.fade-carousel .slides .slide-1 {
  background-image: url(http://i.piccy.info/i9/3c58d5e7860718da0d2b3705eaf088e7/1512668413/33907/1203153/Website_Hosting.jpg); 
}
.fade-carousel .slides .slide-2 {
  background-image: url(http://i.piccy.info/i9/fe91a4d5f27938c88fc95a3b08b700ef/1512668533/91559/1203153/Web_Design.jpg);
}
.fade-carousel .slides .slide-3 {
  background-image: url(http://i.piccy.info/i9/aae07e2f413660ca633c8020e6b61d92/1512668647/88889/1203153/pwa_structure.png);
}


@media screen and (min-width: 980px){
    .hero { width: 980px; }    
}
@media screen and (max-width: 640px){
    .hero h1 { font-size: 4em; }    
}
</style>
<div class="carousel fade-carousel slide" data-ride="carousel" data-interval="4000" id="bs-carousel">

 

  <ol class="carousel-indicators">
    <li data-target="#bs-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#bs-carousel" data-slide-to="1"></li>
    <li data-target="#bs-carousel" data-slide-to="2"></li>
  </ol>
  
 
  <div class="carousel-inner">
    <div class="item slides active">
      <div class="slide-1"></div>
      <div class="hero">
        <hgroup>
            <h1>HTML</h1>        
            <h3>Getting started with HTML</h3>
        </hgroup>
        <%= link_to "See book", pages_html_path, class: "btn btn-hero btn-lg"%>
      </div>
    </div>
    <div class="item slides">
      <div class="slide-2"></div>
      <div class="hero">        
        <hgroup>
            <h1>CSS</h1>        
            <h3>Getting started with CSS</h3>
        </hgroup>       
        <%= link_to "See book", pages_css_path, class: "btn btn-hero btn-lg"%>
      </div>
    </div>
    <div class="item slides">
      <div class="slide-3"></div>
      <div class="hero">        
        <hgroup>
            <h1>JavaScript</h1>        
            <h3>Getting started with JavaScript</h3>
        </hgroup>
        <%= link_to "See book", pages_javascript_path, class: "btn btn-hero btn-lg"%>
      </div>
    </div>
  </div> 
</div>

app/views/pages/css.html.erb
<br>
    <div class="container">
        <div class="row">
            <div class="hidden-xs col-sm-4">
                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">Меню</h4>
                        </div>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="/pages/html">HTML</a></li>
                            <li><a href="/pages/css">CSS</a></li>
                            <li><a href="/pages/javascript">JavaScript</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-8">
                <% if current_user != nil and current_user.id == 1 %>
                    <center><%= link_to "Create new learn", new_post_path, class: "btn btn-default" %></center>
                <%end%> 
                    <% @posts.each do |post| %>   
                    <center><h4>• <%= link_to post.title, post_path(post.id) %></h4></center>
                    <%end%>
            </div>
         </div>
    </div>

app/views/pages/html.html.erb
<br>
    <div class="container">
        <div class="row">
            <div class="hidden-xs col-sm-4">
                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">Меню</h4>
                        </div>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="/pages/html">HTML</a></li>
                            <li><a href="/pages/css">CSS</a></li>
                            <li><a href="/pages/javascript">JavaScript</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-8">
                <% if current_user != nil and current_user.id == 1 %>
                    <center><%= link_to "Create new learn", new_post_path, class: "btn btn-default" %></center>
                <%end%> 
                    <% @posts.each do |post| %>
                    <center><h4>• <%= link_to post.title, post_path(post.id) %></h4></center>
                    <%end%>
            </div>
         </div>
    </div>

app/views/pages/index.html.erb
<div class="header">
<%= render 'pages/header' %>
</div>

app/views/pages/javascript.html.erb
<br>
    <div class="container">
        <div class="row">
            <div class="hidden-xs col-sm-4">
                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">Меню</h4>
                        </div>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="/pages/html">HTML</a></li>
                            <li><a href="/pages/css">CSS</a></li>
                            <li><a href="/pages/javascript">JavaScript</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-8">
                <% if current_user != nil and current_user.id == 1 %>
                    <center><%= link_to "Create new learn", new_post_path, class: "btn btn-default" %></center>
                <%end%> 
                    <% @posts.each do |post| %>   
                    <center><h4>• <%= link_to post.title, post_path(post.id) %></h4></center>
                    <%end%>
            </div>
         </div>
    </div>

app/views/postcomments/_elem.html.erb
<p><%= image_tag comment.user.avatar.url(:thumb), width: 30, heigth: 30 %>
 User <b><%= comment.user.nickname %></b> write:</p>
 <div class = "bord">
<i><%= comment.text %></i>
</div>
<div class="time"><span class="glyphicon glyphicon-time"></span>
<small><%= comment.created_at %></small></div>

app/views/postcomments/_form.html.erb
<% if flash[:notice] %>
  <div class="notice"> <%= flash[:notice] %> </div>
<% end %>
<div class="com">
	<p><%= f.label "Comment" %></p>
	<%= f.text_area :text,  class: "content-field", placeholder: "Add a comment"%><br />
 

 <p><%= f.submit "Send" %></p>
 </div>

app/views/posts/_form.html.erb
<p><%= f.label :category %></p>
<%= select_tag 'category_id', options_from_collection_for_select(Category.all, 'id', 'name')%>

  <p><%= f.label :title %></p>
  <%= f.text_field :title %><br />

  <p><%= f.label :body %></p>
	<%= f.text_area :body, :class => "tinymce", :rows => 30, :cols => 80 %>
  <%= tinymce %><br />
 
  <p><%= f.submit "Save" %></p>

app/views/posts/edit.html.erb
<center><%= form_for :post, url:post_path, method: :patch do |f| %>
	<% if @post.errors.any? %>
	 <% @post.errors.full_messages.each do |msg| %>
	 	<li><%=msg%></li>
	   <%end%>
	 <%end%>
<%= render 'posts/form', f:f%>
<%end%></center>

app/views/posts/new.html.erb
<center><%= form_for @post, url: posts_path, validate: true do |f| %>
	<% if @post.errors.any? %>
	 <% @post.errors.full_messages.each do |msg| %>
	 	<li><%=msg%></li>
	   <%end%>
	 <%end%>
	<%= render 'posts/form', f:f%>
<%end%></center>

app/views/posts/show.html.erb
<style>
.com { 
    text-align: center;
    padding: 20px;
}

.bord{
	background: #FFF8DC;
	border: 1px;
	border-style: solid;
	border-color: #DCDCDC;
	border-radius: 20px;
	margin-bottom: 5px;
	padding: 20px;
	margin-right: 15px;
	margin-left: 15px;
}

.ram
{
	margin-right: 15px;
	margin-left: 15px;
}

.time{
	text-align: right;
	opacity: 0.65;
}

.post{
	margin-left: 20px;
	margin-right: 20px;
}
#ed{
	margin-right: 15px;
	opacity: 0.65;
}
</style>
<br>
    <div class="container">
        <div class="row">
            <div class="hidden-xs col-sm-4">
                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">Меню</h4>
                        </div>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="/pages/html">HTML</a></li>
                            <li><a href="/pages/css">CSS</a></li>
                            <li><a href="/pages/javascript">JavaScript</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-8">
                
           

<div class="post">
<div id="ed"><% if current_user != nil and current_user.id == 1 %>
				<%= link_to "Edit",  edit_post_path %> or
				<%= link_to "Delete", post_path, data: {confirm: 'Rili deleted your post?'}, method: :delete %>
			<%end%>
</div>
<center><h1><%= @post.title %></h1></center>
<p><%= sanitize @post.body %></p>

<hr>
</div>

<% @comments.each do |comment|%>
<div class="ram">
<%= render 'postcomments/elem', comment:comment%>
<%= link_to vote_path(comment.id) do%><i class="glyphicon glyphicon-bell"></i><%end%>(<%=@votes[comment.id]%>)
<% end %>

	
<%= form_for :postcomment, url: post_postcomments_path(post_id: @post.id) do |f| %>
<% if flash[:notice] %>
  <div class="notice"> <%= flash[:notice] %> </div>
<% end %>
<div class="com">
	<p><%= f.label "Comment" %></p>
	<%= f.text_area :text,  class: "content-field", placeholder: "Add a comment"%><br />
 

 <p><%= f.submit "Send" %></p>
 </div>
<%end%>
 </div>
         </div>
    </div>